// ─── Static coin data ─────────────────────────────────────────────────────────
const Coins = [
    {
        id: "bitcoin",
        symbol: "BTC",
        name: "Bitcoin",
        image: "https://assets.coingecko.com/coins/images/1/small/bitcoin.png",
        network: "Bitcoin Network",
        address: "bc1qs9ry030sxak7glydad57k0j5drq43dxr2efvhg",
        minDeposit: "0.0001 BTC",
        confirmations: 2,
    },
    {
        id: "ethereum",
        symbol: "ETH",
        name: "Ethereum",
        image: "https://assets.coingecko.com/coins/images/279/small/ethereum.png",
        network: "Ethereum (ERC-20)",
        address: "0x46B93a9B1F8945E3b60d4f940C36A96398d0092B",
        minDeposit: "0.01 ETH",
        confirmations: 12,
    },
    {
        id: "tether",
        symbol: "USDT",
        name: "Tether",
        image: "https://assets.coingecko.com/coins/images/325/small/Tether.png",
        network: "Tron (TRC-20)", 
        address: "THUVhXrd1ohR4yZZVWoyKNdF6HNcs2hQyH",
        minDeposit: "10 USDT",
        confirmations: 12,
    },
    {
        id: "binancecoin",
        symbol: "BNB",
        name: "BNB",
        image: "https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png",
        network: "BNB Smart Chain (BEP-20)",
        address: "0x46B93a9B1F8945E3b60d4f940C36A96398d0092B",
        minDeposit: "0.01 BNB",
        confirmations: 15,
    },
    {
        id: "solana",
        symbol: "SOL",
        name: "Solana",
        image: "https://assets.coingecko.com/coins/images/4128/small/solana.png",
        network: "Solana Network",
        address: "9hRZrJxWQhgYtQeEmZgYsAWvAi3TPjoUdHoqaqHxCUQv",
        minDeposit: "0.01 SOL",
        confirmations: 32,
    },
];

export default Coins;