import { CreditCard, Building2, Wallet, Send } from "lucide-react";

const DepositMethods = [
    {
        id: "card",
        label: "Card",
        subtext: "Pay with debit or credit card via Paybis",
        icon: CreditCard,
        accent: "text-accent",
        bg: "bg-accent/10",
        border: "hover:border-accent/50",
        tag: "Instant",
        tagColor: "bg-success/10 text-success",
        provider: "paybis",
    },
    {
        id: "iban",
        label: "Bank Transfer (IBAN)",
        subtext: "Direct SEPA / Wire transfer to our official bank account",
        icon: Building2,
        accent: "text-warning",
        bg: "bg-warning/10",
        border: "hover:border-warning/40",
        tag: "1-3 days",
        tagColor: "bg-warning/10 text-warning",
        provider: null,
        details: {
            bankName: "Post-Bank",
            accountName: "Marko Coric",
            iban: "DE44 1001 00100078 0861 18",
            bicSwift: "PBNKDEFFXXX",
        },
    },
    {
        id: "paypal",
        label: "PayPal",
        subtext: "Instant transfer via PayPal to our dedicated account",
        icon: Send,
        accent: "text-accent",
        bg: "bg-accent/10",
        border: "hover:border-accent/40",
        tag: "Instant",
        tagColor: "bg-success/10 text-success",
        provider: null,
        details: {
            email: "markocoric690@gmail.com",
            paypalMe: "https://paypal.me/markocoric",
            note: "*Note: Send through 'Friends and Family' option only.",
        },
    },
    {
        id: "wallet",
        label: "External Wallet",
        subtext: "Send from any external crypto wallet directly",
        icon: Wallet,
        accent: "text-success",
        bg: "bg-success/10",
        border: "hover:border-success/40",
        tag: "On-chain",
        tagColor: "bg-accent/10 text-accent",
        provider: null,
    },
];

export default DepositMethods;